
from .__init__ import AIType, BotType


__BOT_TO_AI = { 
    BotType.W2V_GLOVE_BASELINE_GUESSER : AIType.BASELINE,
    BotType.W2V_BASELINE_GUESSER : AIType.BASELINE,
    BotType.GLOVE_50_BASELINE_GUESSER : AIType.BASELINE,
    BotType.GLOVE_100_BASELINE_GUESSER : AIType.BASELINE,
    BotType.GLOVE_200_BASELINE_GUESSER : AIType.BASELINE,
    BotType.GLOVE_300_BASELINE_GUESSER : AIType.BASELINE,
    BotType.CN_NB_BASELINE_GUESSER : AIType.BASELINE,
    BotType.D2V_BASELINE_GUESSER : AIType.BASELINE,
    BotType.ELMO_BASELINE_GUESSER : AIType.BASELINE,
    BotType.BERT1_BASELINE_GUESSER : AIType.BASELINE,
    BotType.BERT2_BASELINE_GUESSER : AIType.BASELINE,
    BotType.FAST_TEXT_BASELINE_GUESSER : AIType.BASELINE,
    
    BotType.W2V_DISTANCE_ASSOCIATOR : AIType.DISTANCE_ASSOCIATOR,
    BotType.GLOVE_300_DISTANCE_ASSOCIATOR : AIType.DISTANCE_ASSOCIATOR,
    BotType.GLOVE_50_DISTANCE_ASSOCIATOR : AIType.DISTANCE_ASSOCIATOR,
    BotType.GLOVE_100_DISTANCE_ASSOCIATOR : AIType.DISTANCE_ASSOCIATOR,
    BotType.GLOVE_200_DISTANCE_ASSOCIATOR : AIType.DISTANCE_ASSOCIATOR,
    BotType.GLOVE_300_DISTANCE_ASSOCIATOR : AIType.DISTANCE_ASSOCIATOR,
    BotType.W2V_GLOVE_DISTANCE_ASSOCIATOR : AIType.DISTANCE_ASSOCIATOR,
    BotType.CN_NB_DISTANCE_ASSOCIATOR : AIType.DISTANCE_ASSOCIATOR,
    BotType.D2V_DISTANCE_ASSOCIATOR : AIType.DISTANCE_ASSOCIATOR,
    BotType.ELMO_DISTANCE_ASSOCIATOR : AIType.DISTANCE_ASSOCIATOR,
    BotType.BERT1_DISTANCE_ASSOCIATOR : AIType.DISTANCE_ASSOCIATOR,
    BotType.BERT2_DISTANCE_ASSOCIATOR : AIType.DISTANCE_ASSOCIATOR,
    BotType.FAST_TEXT_DISTANCE_ASSOCIATOR : AIType.DISTANCE_ASSOCIATOR,

    BotType.BAYESIAN_SPYMASTER : AIType.BAYESIAN,
    BotType.BAYESIAN_GUESSER : AIType.BAYESIAN,
    BotType.NOISY_GUESSER : AIType.NOISY

    
}

def get_ai(bot_type_key: 'BotType') -> 'AIType':
    return __BOT_TO_AI.get(bot_type_key.strip().split(':', maxsplit=1)[0], None)